import assert from 'node:assert/strict';
import test from 'node:test';
import { BoardHistory, boardToScreen, calculateDrawingBounds, clampZoom, clearBoard, createPenStroke, createShape, createText, deleteSelected, emptyBoard, findObjectAt, hitTestObject, moveObject, screenToBoard, setActiveTool } from '../src/utils/drawingBoard.ts';

test('creates a pen stroke', () => assert.deepEqual(createPenStroke([{ x: 1, y: 2 }]).points, [{ x: 1, y: 2 }]));
for (const type of ['line', 'arrow', 'rectangle', 'ellipse'] as const) test(`creates a ${type}`, () => assert.equal(createShape(type, { x: 0, y: 0 }, { x: 20, y: 10 }).type, type));
test('creates text', () => assert.equal(createText({ x: 2, y: 3 }, 'Hello').text, 'Hello'));
test('selects the topmost object', () => { const first = createShape('rectangle', { x: 0, y: 0 }, { x: 20, y: 20 }); const second = createShape('line', { x: 0, y: 0 }, { x: 20, y: 0 }); assert.equal(findObjectAt([first, second], { x: 10, y: 0 })?.id, second.id); });
test('moves an object', () => { const moved = moveObject(createShape('line', { x: 1, y: 2 }, { x: 4, y: 6 }), 5, 7); assert.deepEqual('start' in moved && moved.start, { x: 6, y: 9 }); });
test('moving preserves shape dimensions', () => { const shape = createShape('rectangle', { x: 1, y: 2 }, { x: 11, y: 22 }); const moved = moveObject(shape, 8, 9); assert.equal('end' in moved && 'start' in moved ? moved.end.x - moved.start.x : 0, 10); assert.equal('end' in moved && 'start' in moved ? moved.end.y - moved.start.y : 0, 20); });
test('line hit testing finds a nearby point', () => assert.equal(hitTestObject(createShape('line', { x: 0, y: 0 }, { x: 100, y: 0 }), { x: 50, y: 3 }), true));
test('rectangle hit testing finds its outline', () => assert.equal(hitTestObject(createShape('rectangle', { x: 0, y: 0 }, { x: 100, y: 50 }), { x: 1, y: 25 }), true));
test('ellipse hit testing finds its outline', () => assert.equal(hitTestObject(createShape('ellipse', { x: 0, y: 0 }, { x: 100, y: 50 }), { x: 50, y: 0 }), true));
test('text hit testing finds its bounds', () => assert.equal(hitTestObject(createText({ x: 10, y: 30 }, 'Test'), { x: 20, y: 20 }), true));
test('pen stroke hit testing follows segments', () => assert.equal(hitTestObject(createPenStroke([{ x: 0, y: 0 }, { x: 100, y: 100 }]), { x: 50, y: 52 }), true));
test('undo create', () => { const history = new BoardHistory(); const object = createText({ x: 0, y: 0 }, 'x'); history.commit([object]); assert.deepEqual(history.undo(), []); });
test('redo create', () => { const history = new BoardHistory(); const object = createText({ x: 0, y: 0 }, 'x'); history.commit([object]); history.undo(); assert.equal(history.redo()?.length, 1); });
test('undo and redo move', () => { const history = new BoardHistory(); const object = createText({ x: 0, y: 20 }, 'x'); history.commit([object]); history.commit([moveObject(object, 10, 0)]); const undone = history.undo(); assert.equal(undone?.[0]?.type === 'text' ? undone[0].position.x : -1, 0); const redone = history.redo(); assert.equal(redone?.[0]?.type === 'text' ? redone[0].position.x : -1, 10); });
test('undo delete restores object', () => { const history = new BoardHistory(); const object = createText({ x: 0, y: 20 }, 'x'); history.commit([object]); history.commit([]); assert.equal(history.undo()?.length, 1); });
test('undo clear restores all objects', () => { const history = new BoardHistory(); history.commit([createText({ x: 0, y: 20 }, 'a'), createText({ x: 0, y: 40 }, 'b')]); history.commit([]); assert.equal(history.undo()?.length, 2); });
test('history is bounded', () => { const history = new BoardHistory(3); for (let index = 0; index < 10; index++) history.commit([createText({ x: index, y: 20 }, `${index}`)]); assert.equal(history.length, 3); });
test('zoom increases', () => assert.equal(clampZoom(1.25), 1.25));
test('zoom decreases', () => assert.equal(clampZoom(.8), .8));
test('zoom has a minimum', () => assert.equal(clampZoom(.01), .25));
test('zoom has a maximum', () => assert.equal(clampZoom(20), 4));
test('screen to board accounts for pan and zoom', () => assert.deepEqual(screenToBoard({ x: 30, y: 50 }, { x: 10, y: 10, zoom: 2 }), { x: 10, y: 20 }));
test('board to screen accounts for pan and zoom', () => assert.deepEqual(boardToScreen({ x: 10, y: 20 }, { x: 10, y: 10, zoom: 2 }), { x: 30, y: 50 }));
test('coordinate transforms round trip', () => { const viewport = { x: -18, y: 42, zoom: 1.75 }; const point = { x: 88, y: 31 }; assert.deepEqual(screenToBoard(boardToScreen(point, viewport), viewport), point); });
test('HTML text remains plain object data', () => assert.equal(createText({ x: 0, y: 0 }, '<b>hello</b>').text, '<b>hello</b>'));
test('script-looking text remains plain object data', () => assert.equal(createText({ x: 0, y: 0 }, '<script>alert(1)</script>').type, 'text'));
test('empty board has no objects or selection', () => assert.deepEqual(emptyBoard().objects, []));
test('clear board removes all objects', () => { const state = { ...emptyBoard(), objects: [createText({ x: 0, y: 0 }, 'x')] }; assert.equal(clearBoard(state).objects.length, 0); });
test('delete selected object removes only selection', () => { const one = createText({ x: 0, y: 0 }, 'one'); const two = createText({ x: 0, y: 0 }, 'two'); assert.deepEqual(deleteSelected({ ...emptyBoard(), objects: [one, two], selectedId: one.id }).objects.map((item) => item.id), [two.id]); });
test('active tool switching preserves objects', () => { const state = { ...emptyBoard(), objects: [createText({ x: 0, y: 0 }, 'x')] }; const next = setActiveTool(state, 'rectangle'); assert.equal(next.activeTool, 'rectangle'); assert.equal(next.objects.length, 1); });
test('calculates drawing bounds with padding', () => { const bounds = calculateDrawingBounds([createShape('rectangle', { x: 10, y: 20 }, { x: 110, y: 70 })], 10); assert.deepEqual(bounds, { x: 0, y: 10, width: 120, height: 70 }); });
test('empty drawing has no export bounds', () => assert.equal(calculateDrawingBounds([]), null));
