import assert from 'node:assert/strict';
import test from 'node:test';
import { MAX_DATE_MS, MIN_DATE_MS, datePartsToTimestamp, detectTimestampUnit, formatRelativeTime, parseIntegerTimestamp, timestampToDate } from '../src/utils/timestamp.ts';

test('timestamp 0 is the Unix epoch', () => assert.equal(timestampToDate('0').date.toISOString(), '1970-01-01T00:00:00.000Z'));
test('timestamp 1 is one second after epoch', () => assert.equal(timestampToDate('1').milliseconds, 1000));
test('timestamp -1 is one second before epoch', () => assert.equal(timestampToDate('-1').date.toISOString(), '1969-12-31T23:59:59.000Z'));
test('converts known seconds timestamp', () => assert.equal(timestampToDate('1700000000').date.toISOString(), '2023-11-14T22:13:20.000Z'));
test('converts known milliseconds timestamp', () => assert.equal(timestampToDate('1700000000000').date.toISOString(), '2023-11-14T22:13:20.000Z'));
test('detects seconds independent of sign', () => assert.equal(detectTimestampUnit(-99_999_999_999), 'seconds'));
test('detects milliseconds independent of sign', () => assert.equal(detectTimestampUnit(-1_000_000_000_000), 'milliseconds'));
test('manual milliseconds override changes interpretation', () => assert.equal(timestampToDate('1000', 'milliseconds').date.toISOString(), '1970-01-01T00:00:01.000Z'));
test('rejects invalid text', () => assert.throws(() => timestampToDate('abc'), /Invalid Unix timestamp/u));
test('rejects decimals', () => assert.throws(() => timestampToDate('12.4'), /Invalid Unix timestamp/u));
test('rejects extremely large values', () => assert.throws(() => timestampToDate('999999999999999999999'), /supported JavaScript range/u));
test('supports pre-1970 milliseconds', () => assert.equal(timestampToDate('-1000', 'milliseconds').date.toISOString(), '1969-12-31T23:59:59.000Z'));
test('converts UTC epoch date parts', () => assert.equal(datePartsToTimestamp({ year: 1970, month: 1, day: 1, hour: 0, minute: 0, second: 0 }, 'utc').seconds, 0));
test('converts a known UTC date', () => assert.equal(datePartsToTimestamp({ year: 2023, month: 11, day: 14, hour: 22, minute: 13, second: 20 }, 'utc').seconds, 1_700_000_000));
test('local conversion uses the native local constructor architecture', () => { const p = { year: 2026, month: 8, day: 25, hour: 20, minute: 30, second: 0 }; assert.equal(datePartsToTimestamp(p, 'local').milliseconds, new Date(2026, 7, 25, 20, 30, 0).getTime()); });
test('accepts a leap day', () => assert.match(datePartsToTimestamp({ year: 2024, month: 2, day: 29, hour: 0, minute: 0, second: 0 }, 'utc').date.toISOString(), /^2024-02-29/u));
test('rejects invalid February date', () => assert.throws(() => datePartsToTimestamp({ year: 2023, month: 2, day: 29, hour: 0, minute: 0, second: 0 }, 'utc'), /Invalid/u));
test('rejects invalid month and day', () => assert.throws(() => datePartsToTimestamp({ year: 2024, month: 13, day: 40, hour: 0, minute: 0, second: 0 }, 'utc'), /Invalid/u));
test('supports midnight', () => assert.match(datePartsToTimestamp({ year: 2000, month: 1, day: 1, hour: 0, minute: 0, second: 0 }, 'utc').date.toISOString(), /T00:00:00/u));
test('supports end of day', () => assert.match(datePartsToTimestamp({ year: 2000, month: 1, day: 1, hour: 23, minute: 59, second: 59 }, 'utc').date.toISOString(), /T23:59:59/u));
test('provides ISO, seconds and milliseconds outputs', () => { const value = timestampToDate('1'); assert.equal(value.date.toISOString(), '1970-01-01T00:00:01.000Z'); assert.equal(value.seconds, 1); assert.equal(value.milliseconds, 1000); });
test('formats relative past', () => assert.match(formatRelativeTime(0, 5 * 60_000, 'en'), /5 minutes ago/u));
test('formats relative future', () => assert.match(formatRelativeTime(2 * 3_600_000, 0, 'en'), /in 2 hours/u));
test('formats near-current as now', () => assert.equal(formatRelativeTime(20_000, 0, 'en'), 'now'));
test('unexpected and HTML-looking input remains rejected data', () => { for (const value of ['🙂', '<b>0</b>', '<script>alert(1)</script>']) assert.equal(parseIntegerTimestamp(value), null); });
test('supports JavaScript Date minimum and maximum', () => { assert.equal(timestampToDate(String(MIN_DATE_MS), 'milliseconds').milliseconds, MIN_DATE_MS); assert.equal(timestampToDate(String(MAX_DATE_MS), 'milliseconds').milliseconds, MAX_DATE_MS); });
test('rejects outside JavaScript Date boundaries', () => assert.throws(() => timestampToDate(String(MAX_DATE_MS + 1), 'milliseconds'), /supported/u));
test('unit detection documents both heuristic boundaries', () => { assert.equal(detectTimestampUnit(99_999_999_999), 'seconds'); assert.equal(detectTimestampUnit(100_000_000_000), 'ambiguous'); assert.equal(detectTimestampUnit(999_999_999_999), 'ambiguous'); assert.equal(detectTimestampUnit(1_000_000_000_000), 'milliseconds'); });
test('Auto rejects ambiguous values', () => assert.throws(() => timestampToDate('100000000000'), /Ambiguous/u));
